##Manipulando texto
A biblioteca stringr tem algumas funções para manipulação de texto (strings). Esse pacote é carregado quando carregamos tidyverse.

Use library(stringr) para usar só stringr. Algumas funções:

[ nchar() ]

str_length: quantidade de caracteres no texto

str_to_upper: deixa tudo MAIÚSCULO

str_to_lower: deixa tudo minúsculo

str_to_title: cada palavra fica com a primeira Maiúscula

str_trim: tira espaços a mais no começo ou final de texto

str_sub: extrai parte de um texto

str_split: separa texto

In [ ]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ purrr::%||%()   masks base::%||%()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [ ]:
## str_length() - número de caracteres em cada texto(String)
estados <- c("Acre", "São Paulo", "Rio de Janeiro", "Minas Gerais", "Goiás")
str_length(estados)
length(estados)

[1]  4  9 14 12  5

[1] 5

In [ ]:
str_to_upper(estados)
str_to_lower(estados)
str_to_title(estados)

[1] "ACRE"           "SÃO PAULO"      "RIO DE JANEIRO" "MINAS GERAIS"
[5] "GOIÁS"

[1] "acre"           "são paulo"      "rio de janeiro" "minas gerais"
[5] "goiás"

[1] "Acre"           "São Paulo"      "Rio De Janeiro" "Minas Gerais"
[5] "Goiás"

In [ ]:
"Acre" == "Acre  "

[1] FALSE

In [ ]:
"acre" == "Acre"

[1] FALSE

In [ ]:
genero <- c("F", " F", "M", " M")
genero
str_trim(genero)

str_trim(estados)

[1] "F"  " F" "M"  " M"

[1] "F" "F" "M" "M"

[1] "Acre"           "São Paulo"      "Rio de Janeiro" "Minas Gerais"
[5] "Goiás"

In [ ]:
genero <- c("F - Feminino", "M - Masculino", "N - Não Binário")
genero
str_sub(genero, start = 1, end = 1)
str_sub(genero, start = 5)

[1] "F - Feminino"    "M - Masculino"   "N - Não Binário"

[1] "F" "M" "N"

[1] "Feminino"    "Masculino"   "Não Binário"

In [ ]:
cidades <- c("Piracicaba - SP", "Pindamonhagaba", "São Paulo - SP", "Goiânia - GO", "Manaus - AM", "Guarulhos - SP", "Osasco - SP")
str_length(cidades)
str_sub(cidades, start=c(7, 5, 6, 4, 6, 3, 7))
str_sub(cidades, start=str_length(cidades))
str_sub(cidades, start=str_length(cidades)-1)
str_sub(cidades, start=-2)
str_sub(cidades, end=-6)

[1] 15 14 14 12 11 14 11

[1] "caba - SP"    "amonhagaba"   "aulo - SP"    "ânia - GO"    "s - AM"
[6] "arulhos - SP" " - SP"

[1] "P" "a" "P" "O" "M" "P" "P"

[1] "SP" "ba" "SP" "GO" "AM" "SP" "SP"

[1] "SP" "ba" "SP" "GO" "AM" "SP" "SP"

[1] "Piracicaba" "Pindamonh"  "São Paulo"  "Goiânia"    "Manaus"
[6] "Guarulhos"  "Osasco"

In [ ]:
genero2 <- c("Feminino (F)", "Masculino(M)", "Não Binário(N)")
str_sub(genero2, end = -5)
str_sub(genero2, start = -3)

[1] "Feminino"   "Masculin"   "Não Binári"

[1] "(F)" "(M)" "(N)"

In [ ]:
destinos <- c("São Paulo - SP - Brasil",
              "Belo Horizonte - MG - Brasil",
              "Rio de Janeiro - RJ - Brasil",
              "New York - NJ - USA")

In [ ]:
(separados <- str_split(destinos, pattern = " - "))
class(separados)

[[1]]
[1] "São Paulo" "SP"        "Brasil"

[[2]]
[1] "Belo Horizonte" "MG"             "Brasil"

[[3]]
[1] "Rio de Janeiro" "RJ"             "Brasil"

[[4]]
[1] "New York" "NJ"       "USA"

[1] "list"

In [ ]:
##
final <- data.frame(do.call(rbind, separados))

colnames(final) <- c("Cidade", "Estado", "País")

final

  Cidade         Estado País
1 São Paulo      SP     Brasil
2 Belo Horizonte MG     Brasil
3 Rio de Janeiro RJ     Brasil
4 New York       NJ     USA

In [ ]:
# sapply aplica uma função em cada elemento de uma lista
# [[ simplesmente acessa o elemento da lista
# o número que segue indica cada elemento

?sapply

(cidades <- sapply(separados,"[[",1))  # elemento 1 de cada lista
(estados <- sapply(separados,"[[",2))  # elemento 2 de cada lista
(paises  <- sapply(separados,"[[",3))  # elemento 3 de cada lista

destinos2 <- data.frame(Cidade = cidades, Estado = estados, País = paises)

destinos2

[1] "São Paulo"      "Belo Horizonte" "Rio de Janeiro" "New York"

[1] "SP" "MG" "RJ" "NJ"

[1] "Brasil" "Brasil" "Brasil" "USA"

  Cidade         Estado País
1 São Paulo      SP     Brasil
2 Belo Horizonte MG     Brasil
3 Rio de Janeiro RJ     Brasil
4 New York       NJ     USA